/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.ctrlEnfermero;
import modelo.tbEnfermero;

/**
 *
 * @author rodri
 */
public class frmEnfermeros extends javax.swing.JFrame {

    /**
     * Creates new form frmEnfermeros
     */
    public frmEnfermeros() {
        initComponents();
        this.setLocationRelativeTo(this);

    }
    
     public static void initFrmEnfermeros(){
    
        tbEnfermero modelo = new tbEnfermero();
        frmEnfermeros vista = new frmEnfermeros();
        ctrlEnfermero controlador = new ctrlEnfermero(modelo, vista);
        
        vista.setVisible(true);    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtEdadEnfermero = new javax.swing.JTextField();
        txtCorreoEnfermero = new javax.swing.JTextField();
        txtNombreEnfermero = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnLimpiarEn = new javax.swing.JButton();
        btnAgregarEn = new javax.swing.JButton();
        btnEliminarEn = new javax.swing.JButton();
        btnActualizarEn = new javax.swing.JButton();
        txtBuscarEn = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbEnfermeros = new javax.swing.JTable();
        txtPesoEnfermero = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jlbFondo = new javax.swing.JLabel();
        jlbFondoImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 3, 36)); // NOI18N
        jLabel1.setText("Agregar Enfermeros");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 320, -1));

        txtEdadEnfermero.setBackground(new java.awt.Color(204, 255, 255));
        txtEdadEnfermero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txtEdadEnfermero, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 120, 40));

        txtCorreoEnfermero.setBackground(new java.awt.Color(204, 255, 255));
        txtCorreoEnfermero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txtCorreoEnfermero, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 450, 40));

        txtNombreEnfermero.setBackground(new java.awt.Color(204, 255, 255));
        txtNombreEnfermero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNombreEnfermero.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNombreEnfermero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreEnfermeroActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombreEnfermero, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 450, 40));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel2.setText("Nombre:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel3.setText("Edad:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel4.setText("Correo:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        btnLimpiarEn.setBackground(new java.awt.Color(204, 255, 204));
        btnLimpiarEn.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnLimpiarEn.setText("Limpiar");
        btnLimpiarEn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarEnActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiarEn, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, 110, 40));

        btnAgregarEn.setBackground(new java.awt.Color(204, 255, 204));
        btnAgregarEn.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnAgregarEn.setText("Agregar");
        btnAgregarEn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarEnActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarEn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 110, 40));

        btnEliminarEn.setBackground(new java.awt.Color(204, 255, 204));
        btnEliminarEn.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnEliminarEn.setText("Eliminar");
        jPanel1.add(btnEliminarEn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 110, 40));

        btnActualizarEn.setBackground(new java.awt.Color(204, 255, 204));
        btnActualizarEn.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnActualizarEn.setText("Actualizar");
        jPanel1.add(btnActualizarEn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 110, 40));

        txtBuscarEn.setBackground(new java.awt.Color(204, 255, 255));
        txtBuscarEn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtBuscarEn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarEnActionPerformed(evt);
            }
        });
        jPanel1.add(txtBuscarEn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 450, 40));

        jtbEnfermeros.setBackground(new java.awt.Color(204, 255, 255));
        jtbEnfermeros.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtbEnfermeros.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtbEnfermeros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtbEnfermeros.setSelectionBackground(new java.awt.Color(204, 204, 255));
        jScrollPane1.setViewportView(jtbEnfermeros);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, 500, 360));

        txtPesoEnfermero.setBackground(new java.awt.Color(204, 255, 255));
        txtPesoEnfermero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txtPesoEnfermero, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, 130, 40));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel5.setText("Peso:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel6.setText("Buscar:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, -1, -1));
        jPanel1.add(jlbFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 70, -1, -1));

        jlbFondoImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoenfermero.jpg"))); // NOI18N
        jlbFondoImage.setText("jLabel7");
        jPanel1.add(jlbFondoImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreEnfermeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreEnfermeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreEnfermeroActionPerformed

    private void btnLimpiarEnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarEnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarEnActionPerformed

    private void btnAgregarEnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarEnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarEnActionPerformed

    private void txtBuscarEnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarEnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarEnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEnfermeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEnfermeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEnfermeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEnfermeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                initFrmEnfermeros();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnActualizarEn;
    public javax.swing.JButton btnAgregarEn;
    public javax.swing.JButton btnEliminarEn;
    public javax.swing.JButton btnLimpiarEn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel jlbFondo;
    private javax.swing.JLabel jlbFondoImage;
    public javax.swing.JTable jtbEnfermeros;
    public javax.swing.JTextField txtBuscarEn;
    public javax.swing.JTextField txtCorreoEnfermero;
    public javax.swing.JTextField txtEdadEnfermero;
    public javax.swing.JTextField txtNombreEnfermero;
    public javax.swing.JTextField txtPesoEnfermero;
    // End of variables declaration//GEN-END:variables
}
